---
title: "Data Science, Computational Social Science, Big Data: Programmieren für Sozialwissenschaftler_innen" 
subtitle: "Google Trends"
author: "Laura Kiemes 12250912 & Felix Grams 12293142"
date: "`r Sys.Date()`"
output:
  word_document:
    toc: no
  pdf_document:
    toc: yes
    toc_depth: 1
  html_document:
    toc: yes
    toc_depth: 2
    toc_float:
      collapsed: yes
toc-title: Inhalt
---
R version 4.2.0 (2022-04-22)  
Platform: x86_64-apple-darwin17.0 (64-bit)  
Running under: macOS Monterey 12.4

# Vorbereitungen

```{r packages verwenden und ordner erstellen, message=FALSE, warning=FALSE}
here::i_am("Googletrends.Rmd") # Dateibezug

# Falls pacman nicht installiert ist wird es installiert und geladen
if (!require("pacman")) install.packages("pacman"); library(pacman)

# Falls pakete nicht installiert sind werden sie installiert und Pakete werden geladen
pacman::p_load(tidyverse, gtrendsR, ggsci, lubridate, scales) 

dir.create("plots") # Ordner erstellen fuer Plots 
dir.create("tables") # Ordner erstellen fuer Tabellen

date_analysis <- ymd("2022-07-01") # Referenzdatum
```

```{r farben locuszoom fuer visualisierungen}
show_col(pal_locuszoom("default")(5))
colors_locuszoom <- c("#D43F3AFF", "#EEA236FF", "#5CB85CFF", "#46B8DAFF", "#357EBDFF")
names(colors_locuszoom) <- c("java", "javascript", "matlab", "typescript", "python")

show_col(pal_locuszoom("default", alpha = 0.5)(5))
colors_locuszoom_light <- c("#D43F3A7F", "#EEA2367F", "#5CB85C7F", "#46B8DA7F", "#357EBD7F")
names(colors_locuszoom_light) <- c("Java", "Javascript", "Matlab", "Typescript", "Python")
```
```{r Variationen fuer loop definieren}
data("countries") # Datensatz zu Laenderbezeichnungen
countries$country_code[which(countries$name == "GERMANY")] # Abkuerzung fuer Deutschland
keywords <- data.frame(
  languages = c("python", "matlab", "java", "typescript", "javascript")) # Schlusselworte Sprachen
geos <- c("DE", "") # interessierende Laender
times <- c("2004-07-01 2022-07-01", # 18 Jahre
           "2017-07-01 2022-07-01", # 5 Jahre
           "2021-07-01 2022-07-01") # 1 Jahr
names(times) <- c("2004", "2017", "2021") # Namen fuer Zeitspannen
names_data <- c("2004_de", "2004_int", 
                "2017_de", "2017_int", 
                "2021_de", "2021_int") # Namen 
list_google_data <- list() # leere Liste zum Fuellen mit Datensaetzen
list_google_plots <- list() # leeere Liste zum Fuellen mit Plots
```

```{r for loop Daten}
i <- 0 # Index zum Mitlaufen

for (k in keywords) {
  for (t in times) {
    for (g in geos) {
      
      i <- i + 1 # Indexzaehler
      print(paste0(i, ". Datensatz")) # Iteration anzeigen
      
      list_google_data[[i]] <- gtrends(
        keyword = k, # Schluesselworte
        geo = g, # Geodaten
        time = t, # Zeitspannen
        gprop = "web", # Websuchen
        category = 0,
        hl = "en-US",
        compared_breakdown = TRUE,
        low_search_volume = FALSE,
        cookie_url = "http://trends.google.com/Cookies/NID",
        tz = 0,
        onlyInterest = FALSE
      )
      
      names(list_google_data)[[i]] <- names_data[[i]] # Namen fuer die Daten
      list_google_data[[i]][["interest_over_time"]] <- list_google_data[[i]][["interest_over_time"]] %>% 
        mutate(hits = as.numeric( # Hits numerisch
          str_remove_all(hits, "<"))) # ohne Kleinerzeichen
      
      print(head(list_google_data[[i]][["interest_over_time"]]))
      

    }
  }
}




```

# Liniendiagramme

```{r for loop Plots}
for (i in 1:length(list_google_data)) {
  
  print(i)

      list_google_plots[[i]] <- ggplot(
        data = list_google_data[[i]][["interest_over_time"]],
        aes(x = as.Date(date), # als Datum
            y = hits, # Anfragen
            group = factor(keyword), # faktorisierte Schluesselworte als Gruppe
            color = keyword)) + # Schluesselworte als Farbe
        geom_line(size = 1) +
        labs(
          x = "Zeit",
          y = "normalisierte, skalierte Aufrufe",
          color = "Suchbegriff", 
          caption = paste0("Datenquelle: Google Trends 
          (https://www.google.com/trends, abgefragt am ", date_analysis, ").")
          ) +
        theme_bw() + # Schwarz-weiss Optik
        theme(
          axis.text.x = element_text(angle = 35, hjust = 1),
          plot.caption = element_text(size = 6, color = "gray60"),
          legend.title = element_text(size = 10),
          legend.text = element_text(size = 8),
          legend.position = "bottom") +
        scale_x_date(date_labels = "%Y",
                     date_breaks = "2 years",
                     date_minor_breaks = "1 year") +
        scale_y_continuous(labels = scales::percent_format(scale = 1)) +
        ggsci::scale_colour_locuszoom() # Farben
      
}

names(list_google_plots) <- names_data # Namen fuer die Plots
```

```{r for loop plot names}
indice_5 <- c(3, 4)
indice_12 <- c(5, 6)

titles <- c(
  "Suchanfragen zu Programmiersprachen in Deutschland",
  "Suchanfragen zu Programmiersprachen weltweit",
  "Suchanfragen zu Programmiersprachen in Deutschland",
  "Suchanfragen zu Programmiersprachen weltweit",
  "Suchanfragen zu Programmiersprachen in Deutschland",
  "Suchanfragen zu Programmiersprachen weltweit"
)

subtitles <- c(
  "seit 2004",
  "seit 2004",
  "innerhalb der letzten fünf Jahre",
  "innerhalb der letzten fünf Jahre",
  "innerhalb der letzten 12 Monate",
  "innerhalb der letzten 12 Monate"
)

for (n in 1:length(list_google_data)) {
  
  list_google_plots[[n]] <- list_google_plots[[n]] + labs(title = titles[[n]], subtitle = subtitles[[n]])
  
  if (n %in% indice_5) { # falls innerhalb der letzten 5 Jahre
    list_google_plots[[n]] <- list_google_plots[[n]] + scale_x_date(date_labels = "%Y",
                                                      date_breaks = "1 years",
                                                      date_minor_breaks = "1 months")
  } else if (n %in% indice_12) { # falls innerhalb der letzten 12 monate
    list_google_plots[[n]] <- list_google_plots[[n]] + scale_x_date(date_labels = "%B %Y",
                                                      date_breaks = "1 months")
  }
  
  print(n) 
  print(list_google_plots[[n]])

  ggsave(filename = paste0("line_", names_data[[n]], ".png"), 
         plot = list_google_plots[[n]], 
         width = 9, height = 5, 
         path = here::here("plots")) # sichern als png

  write_csv(as.data.frame(
    list_google_data[[1]][["interest_over_time"]]), 
    file = here::here("tables", paste0("over_time_", names_data[[n]], ".csv"))) # als csv
}
```

# Karten

```{r weltdaten}
world <- map_data("world") # Weltdaten einlesen

# aendert die Regionnamen zu denen, die Google Trends verwendet 
world <- world %>%
  mutate(region = replace(region, region == "USA", "United States")) %>%
  mutate(region = replace(region, region == "UK", "United Kingdom"))
```

```{r Kartendaten}
data_time_names <- c(2, 4, 6)
list_google_data_maps <- list()

# Laender mit Aufrufen und je einer Programmiersprache

for (d in 1:length(data_time_names)) {
  
  list_google_data_maps[[d]] <- list_google_data[[data_time_names[d]]][["interest_by_country"]] %>%
  filter(location %in% world$region, hits > 0) %>%
  mutate(region = location, 
         hits = as.numeric(str_remove_all(hits, "%"))) %>%
  select(hits, keyword, region) %>%
  group_by(region) %>%
  arrange(region, desc(hits)) %>%
  slice(1)
  
  print(paste0(d, ". Datensatz"))
  print(head(list_google_data_maps[[d]])) 
}
```


```{r Karten nach fuenf Sprachen}
list_google_plots_maps <- list()

for (e in 1:length(list_google_data_maps)) {
  
  print(e)
  
  list_google_plots_maps[[e]] <- ggplot() +
  geom_map(data = world,
           map = world,
           aes(x = long, y = lat, map_id = region),
           fill="#e5e5e5", color="#bababa", size=0.15) +
  geom_map(data = list_google_data_maps[[e]], 
           map = world, 
           aes(fill = keyword, map_id = region, alpha = hits)) +
  ggtitle(paste0("Suchanfragen weltweit seit Juli ", names(times)[e],"*")) +
  theme_void() +
  labs(fill = "Suchwort",
       alpha = "Prozentzahl der 
       Suchanfragen",
       caption = paste0("*Regionen mit geringem Suchvolumen grau hinterlegt
       
       Datenquelle: Google Trends 
          (https://www.google.com/trends, abgefragt am ", date_analysis, ").")) +
  scale_fill_manual(values = c(colors_locuszoom["java"], 
                               colors_locuszoom["typescript"], 
                               colors_locuszoom["python"]))
  
  print(list_google_plots_maps[[e]])
  
  ggsave(filename = paste0("map_", names(times)[[e]], ".png"), 
         plot = list_google_plots_maps[[e]], 
         width = 9, height = 5, 
         path = here::here("plots"))
}
```

# Karten pro Programmiersprache

```{r daten fuer karten nach einzelnen suchbegriffen}
python_data <- gtrends(keyword = "python", geo = "", time = times[3])
typescript_data <- gtrends(keyword = "typescript", geo = "", time = times[3])
matlab_data <- gtrends(keyword = "matlab", geo = "", time = times[3])
java_data <- gtrends(keyword = "java", geo = "", time = times[3])
javascript_data <- gtrends(keyword = "javascript", geo = "", time = times[3])

list_google_data_sep <- list(java_data, javascript_data, matlab_data, typescript_data, python_data)
list_google_plots_sep <- list()
```

```{r karten nach einzelnen suchbegriffen}
for (l in 1:length(keywords$languages)) {
  
  print(l)
  
  list_google_plots_sep[[l]] <- ggplot() +
  geom_map(data = world,
           map = world,
           aes(x = long, y = lat, map_id = region),
           fill="#e5e5e5", color="#bababa", size=0.15) +
  geom_map(data = list_google_data_sep[[l]][["interest_by_country"]] %>%
  filter(location %in% world$region, hits > 0) %>%
  mutate(region = location, 
         hits = as.numeric(str_remove_all(hits, "%"))), 
           map = world, 
           aes(fill = hits, map_id = region)) +
  ggtitle(paste("Suchanfragen zu", names(colors_locuszoom_light)[l], "weltweit seit Juli 2021*")) +
  theme_void() +
  labs(fill = "Anzahl",
       caption = paste0("*Regionen mit geringem Suchvolumen grau hinterlegt
       
       Datenquelle: Google Trends 
          (https://www.google.com/trends, abgefragt am ", date_analysis, ").")) +
  theme(plot.caption = element_text(size = 6, color = "gray60")) +
  scale_fill_continuous(high = colors_locuszoom[l], low = colors_locuszoom_light[l])
  
  print(list_google_plots_sep[[l]])
  
  ggsave(filename = paste0("map_2021_", names(colors_locuszoom_light)[l], ".png"), 
         plot = list_google_plots_sep[[l]], 
         width = 9, height = 5, 
         path = here::here("plots")) # als png
  
}
```

# Verwandte Themen

```{r verwandte themen}
list_related_topics <- list(java = java_data[["related_topics"]]$value,
     javascript = javascript_data[["related_topics"]]$value,
     matlab = matlab_data[["related_topics"]]$value,
     typescript = typescript_data[["related_topics"]]$value,
     python = python_data[["related_topics"]]$value)

dataframe_related_topics <- data_frame(java = rep(NA, 36),
                                       javascript = rep(NA, 36),
                                       matlab = rep(NA, 36),
                                       typescript = rep(NA, 36),
                                       python = rep(NA, 36))

dataframe_related_topics$java <- list_related_topics$java
dataframe_related_topics$javascript[1:29] <- list_related_topics$javascript
dataframe_related_topics$matlab[1:18] <- list_related_topics$matlab
dataframe_related_topics$typescript[1:31] <- list_related_topics$typescript
dataframe_related_topics$python[1:29] <- list_related_topics$python

str(dataframe_related_topics)

write_csv(dataframe_related_topics, 
    file = here::here("tables", "related_topics.csv"))
```

# Verwandte Suchen

```{r aehnliche suchen}
list_related_queries <- list(java = java_data[["related_queries"]]$value,
     javascript = javascript_data[["related_queries"]]$value,
     matlab = matlab_data[["related_queries"]]$value,
     typescript = typescript_data[["related_queries"]]$value,
     python = python_data[["related_queries"]]$value)

dataframe_related_queries <- data_frame(java = rep(NA, 50),
                                       javascript = rep(NA, 50),
                                       matlab = rep(NA, 50),
                                       typescript = rep(NA, 50),
                                       python = rep(NA, 50))

dataframe_related_queries$java <- list_related_queries$java
dataframe_related_queries$javascript <- list_related_queries$javascript
dataframe_related_queries$matlab <- list_related_queries$matlab
dataframe_related_queries$typescript <- list_related_queries$typescript
dataframe_related_queries$python <- list_related_queries$python

str(dataframe_related_queries)

write_csv(dataframe_related_queries, 
    file = here::here("tables", "related_queries.csv"))
```